package mybatis.es.dao;

import java.util.List;
import java.util.Map;

import mybatis.es.pojo.Es;

public interface EsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es
     *
     * @mbggenerated
     */
    int insert(Es record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es
     *
     * @mbggenerated
     */
    Es selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es
     *
     * @mbggenerated
     */
    java.util.List<mybatis.es.pojo.Es> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Es record);
    
    int insertLogs(List<Map> lists);
}