package mybatis.es.pojo;

public class Es {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column es.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es.id
     *
     * @return the value of es.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es.id
     *
     * @param id the value for es.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es.value
     *
     * @return the value of es.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es.value
     *
     * @param value the value for es.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value;
    }
}